# ----------------------------------------
# BEGIN CONFIGURATION
# ----------------------------------------
#
# ----------------------------------------
# Application configuration
app:
  # Application mode
  # development or production
  # Default: production
  mode: "production"
  # Dashboard path
  # Default Dashboard
  # Allowed characters [a-z0-9]([a-z0-9_-]?[a-z0-9])? case insensitive
  dashboard_path: "dashboard"
  # Session name
  #  used to store session id in cookie
  # session name must be ([a-zA-Z0-9_-]+)
  # default: vault
  session_name: vault
  # CSRF token duration in minutes
  # minimum: 5 minutes, maximum: 86400 (1 day)
  # default: 30 minutes
  csrf_durations: 30
  # Secret key used to encrypt the sensitive content / data
  # default: (empty)
  secret_key: "change-this-to-a-random-secret-string"
  # Salt key used to encrypt sensitive data
  # default: (empty)
  salt_key: "change-this-to-a-random-salt-string"
  # Default user run as (affected on root permissions)
  # default: (empty) auto-detect binary owner
  user: ""
  # List of TCP Listen addresses
  # used for multiple binding
  # only localhost is supported for non-IP addresses
  # Default: [127.0.0.1:55155]
  tcp:
    - "127.0.0.1:55080"
  # SSL Configuration
  # 443 always
  ssl:
    # Auto create ssl
    auto_create: bool
    # Listen SSL Address
    listen:
      - "127.0.0.1:55443"
    # certificate file path
    cert: ""
    # certificate key file path
    key: ""
    # SSL Session cache size in MB
    # minimum: 2, maximum: 256
    # default : 32
    ssl_session_cache: 32
    # SSL certificate config based on domain / IP
    # default (empty)
    domains:
      # Specify per user domains
      # supported IP
      # use *.example.com for wildcard
      "127.0.0.1":
        cert: ""
        key: ""

  # Max worker
  # default: 0 (auto detect - use available cores)
  workers: 0
  # Operation timeout in seconds for non websocket operations
  # minimum: 1, maximum: 3600
  # Default: 10
  operation_timeout: 10
  # Request timeout in seconds
  # minimum: 0, maximum: 3600
  # Default: 10
  # 0 mean disable
  request_timeout: 10
  # Disconnect timeout in seconds
  # minimum: 0, maximum: 3600
  # Default: 5
  disconnect_timeout: 5
  # Maximum number of concurrent connections
  # maximum: 65535, minimum: 128
  # Default: 25K / 25000
  max_connections: 25000
  # Sets the per-worker maximum concurrent TLS connection limit.
  # All listeners will stop accepting connections when this limit is reached. It can be used to limit the global TLS CPU usage.
  # minimum: 32, maximum: 65535
  # Default: 0 (auto calculation)
  max_connections_rate: 0
  # Backlog size for the server socket
  # maximum: 65535, minimum: 128 (maximum recommended is: 8192)
  # Default: 4096
  backlog: 4096
  # Rlimit nofile
  # The maximum number of open file descriptors that the process can have.
  # maximum: 1048576, minimum: 4096
  # Default: 65535
  rlimit_nofile: 65535
  # Keep-alive connection
  # minimum: 0, maximum: 7200
  # Default: 75
  # 0 means disabled
  keep_alive: 75
  # Auto clean memory
  # Default: true
  auto_clean_memory: true
  # Auto clean memory threshold
  # minimum: 128MB
  # Default: 384MB
  # Without unit it will be used bytes as unit
  auto_clean_memory_size: "384M"
  # Auto clean memory interval in seconds
  # If you need to use this feature, recommended using every 5 minutes (300)
  # minimum: 30 (30 seconds), maximum: 1 month = 30 days * 24 hours * 60 minutes
  # Default: 1H
  # Without unit it will be used second as unit
  # Uppercase M as Month, as lowercase m as Minute
  auto_clean_memory_interval: "1H"
# ----------------------------------------
# Redis configuration
# Use Redis
redis:
  # Unix socket path
  # Default: (empty)
  unix_socket: ""
  # Redis host
  # Default: localhost
  host: localhost
  # Redis port
  # Default: 6379
  port: 6379
  # Redis username
  # Default: (empty)
  username: ""
  # Redis password
  # Default: (empty)
  password: ""
  # Redis database
  # minimum: 0, maximum: 16
  # Default: 0
  database: 0
  # Maximum pools
  # minimum: 1, maximum: 128
  # Default: 10
  max_pools: 10
  # Minimum number of idle connections in the pool
  # minimum: 1, maximum: 64
  # Default: 1
  minimum_idle_connections: 1
  # Idle connection timeout in seconds
  # minimum: 1, maximum: 86400 (1 day)
  # Default: 600
  idle_timeout: 600
  # Connection timeout in seconds
  # minimum: 1, maximum: 3600
  # Default: 5
  connect_timeout: 5
# ----------------------------------------
# Database configuration
# Database connection pool settings
# Use PostgreSQL
database:
  # Database driver
  # postgresql, sqlite, mysql
  driver: "postgresql"
  # Unix socket path
  # Default: (empty)
  socket: null
  # Database host
  # Default: localhost
  host: localhost
  # Database port
  # Default: 5432
  port: 5432
  # Database username
  # Default: (empty)
  username: ""
  # Database password
  password: ""
  # Database name
  # Default: (empty)
  database: ""
  # Maximum number of connections in the pool
  # Default: 50
  max_connections: 50
  # Minimum number of idle connections in the pool
  # Default: 1
  min_connections: 1
  # Connection acquisition timeout in seconds
  # Default: 1800
  max_lifetime: 1800
  # Statement timeout in seconds
  # Default: 5
  statement_timeout: 5
  # Idle connection timeout in seconds
  # Default: 600
  idle_timeout: 600
  # Connection timeout in seconds
  # Default: 10
  acquire_timeout: 10
  # Enable logging
  # Default: false
  log_enable: false
  # Log level
  # debug, info, warn, error, off
  # Default: Warn
  log_level: "warn"
  # Log slow queries
  # debug, info, warn, error, off
  # Default: error
  log_slow_level: "error"
  # Log threshold in seconds
  # Default: 1
  log_threshold: 1
  # Collation (only for MySQL)
  # Default: utf8mb4_general_ci
  collation: "utf8mb4_general_ci"
# ----------------------------------------
# Licenses / API Key based on requirements
#
licenses:
  # maxmind geo api key
  maxmind: ""
  # put any other license configuration here

# ----------------------------------------
# END
# ----------------------------------------
